### ISSUE TITLE
Blacklist

### ISSUE THREAD

**Issue by mattmartinez2006** [robmarkcole/HASS-Sighthound#27]
I tried to add this into HACS and it said that this repo is in the blacklist. Was curious if its possible for it to be un-blacklisted

**Comment by robmarkcole** [comment]
I have no idea about that

**Comment by kifort** [comment]
Blacklist reason was "Repository is archived"
See https://github.com/hacs/default/commit/e2406aa355961f9823f2bf796a16ad4d6c4538f8

**Comment by robmarkcole** [comment]
It was archived at some point when the features were even with the 'official' integration, then unarchived when new features were added in this branch

**Comment by kifort** [comment]
Makes sense. I hope, HACS will enable it again.

**Comment by robmarkcole** [comment]
People can add to hacs manually, closing

**Comment by kifort** [comment]
@robmarkcole , "People can add to hacs manually": is this actually true? When I add this repo manually as a custom repository, HACS rejects it with an error message of "Repository is in the blacklist."

**Comment by robmarkcole** [comment]
I dont use HACS myself, I guess it should be removed from black list. All HACS does is git clone
