### ISSUE TITLE
Defocus event unknown

### ISSUE THREAD

**Issue by jeyrb** [robmarkcole/HASS-Sighthound#9]
My Hikvision ANPR camera throws out lots of ‘defocus‘ events, which aren’t in the list of event constants for pyhik and fill the hass log with errors. It’s one of the Smart Events on the camera, though switching those off in the config UI makes no difference. Possible to add this event name to the list?

**Comment by robmarkcole** [comment]
This sounds like an issue/FR for the camera component. Can you provide some more context?

**Comment by jeyrb** [comment]
Ah, you’re right, it’s a pyhik fix rather than a Hass one. Been a while since I patched it
